pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sanjal29/nginx-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %DOCKER_IMAGE%:%IMAGE_TAG% app/'
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {

                    bat 'docker login -u %USERNAME% -p %PASSWORD%'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                bat 'docker push %DOCKER_IMAGE%:%IMAGE_TAG%'
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                bat '''
powershell -Command "(Get-Content k8s-manifests/deployment.yaml) -replace 'sanjal29/nginx-app:.*','%DOCKER_IMAGE%:%IMAGE_TAG%' | Set-Content k8s-manifests/deployment.yaml"
'''
            }
        }

        stage('Commit & Push Changes to GitHub') {
            steps {

                withCredentials([usernamePassword(
                    credentialsId: 'github-cred-f',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_PASSWORD'
                )]) {

                    bat '''
git config user.email "jenkins@example.com"
git config user.name "jenkins"

git pull origin main

git add k8s-manifests/deployment.yaml

git commit -m "Updated image to %IMAGE_TAG%" --allow-empty

git push https://%GIT_USERNAME%:%GIT_PASSWORD%@github.com/SANJAL-COMCAST/cicd-nginx-app.git HEAD:main
'''
                }
            }
        }

    }
}